spring:
  application:
    name: praksaFakture
  datasource:
    url: jdbc:oracle:thin:@192.168.56.101:1521:xe
    username: jcvetko
    password: 1738
    driver-class-name: oracle.jdbc.OracleDriver

server:
  port: 6464

jwt:
  secret: this-is-a-very-long-secret-key-that-is-at-least-32-characters